//	Copyright (C) 2012 Travis Whitaker

#include <gmp.h>
#include <ptable.h>


char *portstrcpy(char dest[], const char source[]);

void popPtable()
{

	elementPop = &hydrogen;
	Elements[0] = &hydrogen;

	elementPop->atomNumber = 1;
	portstrcpy(elementPop->atomSymbol,"H");
    portstrcpy(elementPop->atomName,"Hydrogen");
	mpf_init_set_str(elementPop->atomMass,"1.00794",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-259.14",10);
    mpf_init_set_str(elementPop->vaporP,"-252.87",10);
    mpf_init_set_str(elementPop->density,"0.00000899",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"1270.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);
    mpf_init_set_str(elementPop->thermCon,"0.01805",10);
    elementPop->metalloid = -1;
    elementPop->magType = 0;
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000132",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"2.2",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.755",10);
    mpf_init_set_str(elementPop->ionE1,"13.598",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"285.8",10);
    mpf_init_set_str(elementPop->atomRadius,"25.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"75.0",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.15",10);
    mpf_init_set_str(elementPop->humanAbundance,"10.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1",10);
    portstrcpy(elementPop->CASn,"1333-74-0");
    portstrcpy(elementPop->CIDn,"783");

	elementPop = &helium;
	Elements[1] = &helium;

	elementPop->atomNumber = 2;
	portstrcpy(elementPop->atomSymbol,"He");
	portstrcpy(elementPop->atomName,"Helium");
	mpf_init_set_str(elementPop->atomMass,"4.002602",10);
	elementPop->phase = 0;
	mpf_init_set_str(elementPop->fusionP,"-1.0",10);
	mpf_init_set_str(elementPop->vaporP,"-268.93",10);
	mpf_init_set_str(elementPop->density,"0.0001785",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
	mpf_init_set_str(elementPop->soundSpeed,"970.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);
	mpf_init_set_str(elementPop->thermCon,"0.1513",10);
	elementPop->metalloid = 2;
	elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
	portstrcpy(elementPop->color,"colorless");
	mpf_init_set_str(elementPop->refractiveIndex,"1.000035",10);
	elementPop->valence = 0;
	mpf_init_set_str(elementPop->electroneg,"0.0",10);
	mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
	mpf_init_set_str(elementPop->ionE1,"24.587",10);
	mpf_init_set_str(elementPop->ionE2 ,"54.418",10);
	mpf_init_set_str(elementPop->ionE3,"-1.0",10);
	mpf_init_set_str(elementPop->mHc,"-1.0",10);
	mpf_init_set_str(elementPop->atomRadius,"31.0",10);
	mpf_init_set_str(elementPop->universeAbundance,"23.0",10);
	mpf_init_set_str(elementPop->crustAbundance,"0.00000055",10);
	mpf_init_set_str(elementPop->humanAbundance,"-1.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
	portstrcpy(elementPop->CASn,"7440-59-7");
	portstrcpy(elementPop->CIDn,"23987");

	elementPop = &lithium;
	Elements[2] = &lithium;

	elementPop->atomNumber = 3;
	portstrcpy(elementPop->atomSymbol,"Li");
    portstrcpy(elementPop->atomName,"Lithium");
    mpf_init_set_str(elementPop->atomMass,"6.941",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"180.54",10);
    mpf_init_set_str(elementPop->vaporP,"1342.0",10);
    mpf_init_set_str(elementPop->density,"0.535",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.6",10);
	mpf_init_set_str(elementPop->youngsModulus,"4.9",10);
    mpf_init_set_str(elementPop->soundSpeed,"6000.0",10);
	mpf_init_set_str(elementPop->thermalExp,"0.000046",10);	
    mpf_init_set_str(elementPop->thermCon,"85.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
    mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
	portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"0.98",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.618",10);
    mpf_init_set_str(elementPop->ionE1,"5.391",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"298.0",10);
    mpf_init_set_str(elementPop->atomRadius,"145.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0000006",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.0017",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.000003",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-93-2");
    portstrcpy(elementPop->CIDn,"3028194");

	elementPop = &beryllium;
	Elements[3] = &beryllium;

	elementPop->atomNumber = 4;
	portstrcpy(elementPop->atomSymbol,"Be");
    portstrcpy(elementPop->atomName,"Beryllium");
    mpf_init_set_str(elementPop->atomMass,"9.012182",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1287.0",10);
    mpf_init_set_str(elementPop->vaporP,"2480.0",10);
    mpf_init_set_str(elementPop->density,"1.858",10);
	mpf_init_set_str(elementPop->mohsHardness,"5.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"287.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"12000.0",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000113",10);	
    mpf_init_set_str(elementPop->thermCon,"190.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"0.026",10);
    portstrcpy(elementPop->color,"slate gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.57",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"9.323",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"105.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0000001",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.00019",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.00000004",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-41-7");
    portstrcpy(elementPop->CIDn,"5460467");

	elementPop = &boron;
	Elements[4] = &boron;

	elementPop->atomNumber = 5;
	portstrcpy(elementPop->atomSymbol,"B");
    portstrcpy(elementPop->atomName,"Boron");
    mpf_init_set_str(elementPop->atomMass,"10.811",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"2075.0",10);
    mpf_init_set_str(elementPop->vaporP,"4000.0",10);
    mpf_init_set_str(elementPop->density,"2.46",10);
	mpf_init_set_str(elementPop->mohsHardness,"9.3",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"16200",10);
	mpf_init_set_str(elementPop->thermalExp,"0.000006",10);	
    mpf_init_set_str(elementPop->thermCon,"27.0",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"black");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"2.04",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.277",10);
    mpf_init_set_str(elementPop->ionE1,"8.298",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"85.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0000001",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.00086",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0000007",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-42-8");
    portstrcpy(elementPop->CIDn,"5462311");

	elementPop = &carbon;
	Elements[5] = &carbon;

	elementPop->atomNumber = 6;
	portstrcpy(elementPop->atomSymbol,"C");
    portstrcpy(elementPop->atomName,"Carbon");
    mpf_init_set_str(elementPop->atomMass,"12.0107",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"3550.0",10);
    mpf_init_set_str(elementPop->vaporP,"4027.0",10);
    mpf_init_set_str(elementPop->density,"2.26",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"18350.0",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000071",10);	
    mpf_init_set_str(elementPop->thermCon,"140.0",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"black");
    mpf_init_set_str(elementPop->refractiveIndex,"2.417",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"2.55",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.595",10);
    mpf_init_set_str(elementPop->ionE1,"11.261",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"70",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.5",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.18",10);
    mpf_init_set_str(elementPop->humanAbundance,"23.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-44-0");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &nitrogen;
	Elements[6] = &nitrogen;

	elementPop->atomNumber = 7;
	portstrcpy(elementPop->atomSymbol,"N");
    portstrcpy(elementPop->atomName,"Nitrogen");
    mpf_init_set_str(elementPop->atomMass,"14.0067",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-210.1",10);
    mpf_init_set_str(elementPop->vaporP,"-195.79",10);
    mpf_init_set_str(elementPop->density,"0.001251",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"333.6",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.02583",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000298",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"3.04",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.07",10);
    mpf_init_set_str(elementPop->ionE1,"14.534",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"65.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.1",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.002",10);
    mpf_init_set_str(elementPop->humanAbundance,"2.6",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7727-37-9");
    portstrcpy(elementPop->CIDn,"947");
	
	elementPop = &oxygen;
	Elements[7] = &oxygen;

	elementPop->atomNumber = 8;
	portstrcpy(elementPop->atomSymbol,"O");
    portstrcpy(elementPop->atomName,"Oxygen");
    mpf_init_set_str(elementPop->atomMass,"15.9994",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-218.3",10);
    mpf_init_set_str(elementPop->vaporP,"-182.9",10);
    mpf_init_set_str(elementPop->density,".001429",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"317.5",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.02658",10);
    elementPop->metalloid = 2;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000271",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"3.44",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.46",10);
    mpf_init_set_str(elementPop->ionE1,"13.618",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"60.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"1.0",10);
    mpf_init_set_str(elementPop->crustAbundance,"46.0",10);
    mpf_init_set_str(elementPop->humanAbundance,"61.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7782-44-7");
    portstrcpy(elementPop->CIDn,"977");

	elementPop = &fluorine;
	Elements[8] = &fluorine;

	elementPop->atomNumber = 9;
	portstrcpy(elementPop->atomSymbol,"F");
    portstrcpy(elementPop->atomName,"Fluorine");
    mpf_init_set_str(elementPop->atomMass,"18.9984032",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-219.6",10);
    mpf_init_set_str(elementPop->vaporP,"-188.12",10);
    mpf_init_set_str(elementPop->density,"0.001696",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.0277",10);
    elementPop->metalloid = 2;
    elementPop->magType = -1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000195",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"3.98",10);
    mpf_init_set_str(elementPop->electroAffinity,"3.4",10);
    mpf_init_set_str(elementPop->ionE1,"17.422",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"50.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.00004",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.054",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0037",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7782-41-4");
    portstrcpy(elementPop->CIDn,"24524");

	elementPop = &neon;
	Elements[9] = &neon;

	elementPop->atomNumber = 10;
	portstrcpy(elementPop->atomSymbol,"Ne");
    portstrcpy(elementPop->atomName,"Neon");
    mpf_init_set_str(elementPop->atomMass,"20.1791",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-248.59",10);
    mpf_init_set_str(elementPop->vaporP,"-246.08",10);
    mpf_init_set_str(elementPop->density,"0.0009",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"936.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.0491",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000067",10);
    elementPop->valence = 0;
    mpf_init_set_str(elementPop->electroneg,"0.0",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"21.565",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"38.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.13",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.0000003",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-01-9");
    portstrcpy(elementPop->CIDn,"23935");

	elementPop = &sodium;
	Elements[10] = &sodium;

	elementPop->atomNumber = 11;
	portstrcpy(elementPop->atomSymbol,"Na");
    portstrcpy(elementPop->atomName,"Sodium");
    mpf_init_set_str(elementPop->atomMass,"22.98976928",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"97.72",10);
    mpf_init_set_str(elementPop->vaporP,"883",10);
    mpf_init_set_str(elementPop->density,"0.968",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"10",10);
    mpf_init_set_str(elementPop->soundSpeed,"3200",10);
	mpf_init_set_str(elementPop->thermalExp,"0.000071",10);	
    mpf_init_set_str(elementPop->thermCon,"140",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"0.93",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.547",10);
    mpf_init_set_str(elementPop->ionE1,"5.139",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"180.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".002",10);
    mpf_init_set_str(elementPop->crustAbundance,"2.3",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.14",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-23-5");
    portstrcpy(elementPop->CIDn,"5360545");

	elementPop = &magnesium;
	Elements[11] = &magnesium;

	elementPop->atomNumber = 12;
	portstrcpy(elementPop->atomSymbol,"Mg");
    portstrcpy(elementPop->atomName,"Magnesium");
    mpf_init_set_str(elementPop->atomMass,"24.3050",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"650.0",10);
    mpf_init_set_str(elementPop->vaporP,"1090.0",10);
    mpf_init_set_str(elementPop->density,"1.738",10);
	mpf_init_set_str(elementPop->mohsHardness,"2.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"45",10);
    mpf_init_set_str(elementPop->soundSpeed,"4602",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000082",10);	
    mpf_init_set_str(elementPop->thermCon,"160.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.31",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"7.646",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"66.08",10);
    mpf_init_set_str(elementPop->atomRadius,"150.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".06",10);
    mpf_init_set_str(elementPop->crustAbundance,"2.9",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.027",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-95-4");
    portstrcpy(elementPop->CIDn,"5462224");

	elementPop = &aluminium;
	Elements[12] = &aluminium;

	elementPop->atomNumber = 13;
	portstrcpy(elementPop->atomSymbol,"Al");
    portstrcpy(elementPop->atomName,"Aluminium");
    mpf_init_set_str(elementPop->atomMass,"26.9815286",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"660.32",10);
    mpf_init_set_str(elementPop->vaporP,"2519.0",10);
    mpf_init_set_str(elementPop->density,"2.7",10);
	mpf_init_set_str(elementPop->mohsHardness,"2.75",10);
	mpf_init_set_str(elementPop->youngsModulus,"70",10);
    mpf_init_set_str(elementPop->soundSpeed,"5100",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000231",10);	
    mpf_init_set_str(elementPop->thermCon,"235",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"1.175",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"1.61",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.44",10);
    mpf_init_set_str(elementPop->ionE1,"5.985",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"125.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.005",10);
    mpf_init_set_str(elementPop->crustAbundance,"8.1",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.00009",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7429-90-5");
    portstrcpy(elementPop->CIDn,"5359268");

	elementPop = &silicon;
	Elements[13] = &silicon;

	elementPop->atomNumber = 14;
	portstrcpy(elementPop->atomSymbol,"Si");
    portstrcpy(elementPop->atomName,"Silicon");
    mpf_init_set_str(elementPop->atomMass,"28.0855",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"141.04",10);
    mpf_init_set_str(elementPop->vaporP,"2900.0",10);
    mpf_init_set_str(elementPop->density,"2.33",10);
	mpf_init_set_str(elementPop->mohsHardness,"6.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"47",10);
    mpf_init_set_str(elementPop->soundSpeed,"2200",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000026",10);	
    mpf_init_set_str(elementPop->thermCon,"150.0",10);
    elementPop->metalloid = 1;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"1.9",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.385",10);
    mpf_init_set_str(elementPop->ionE1,"8.151",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"9055.0",10);
    mpf_init_set_str(elementPop->atomRadius,"110.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.07",10);
    mpf_init_set_str(elementPop->crustAbundance,"27.0",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.026",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-21-3");
    portstrcpy(elementPop->CIDn,"5461123");


	elementPop = &phosphorus;
	Elements[14] = &phosphorus;

	elementPop->atomNumber = 15;
	portstrcpy(elementPop->atomSymbol,"P");
    portstrcpy(elementPop->atomName,"Phosphorus");
    mpf_init_set_str(elementPop->atomMass,"30.973762",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"-1.0",10);
    mpf_init_set_str(elementPop->vaporP,"-1.0",10);
    mpf_init_set_str(elementPop->density,"-1.0",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.236",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"white/black/red");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"2.19",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.75",10);
    mpf_init_set_str(elementPop->ionE1,"10.487",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"100.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0007",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.099",10);
    mpf_init_set_str(elementPop->humanAbundance,"1.1",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7723-14-0");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &sulfur;
	Elements[15] = &sulfur;

	elementPop->atomNumber = 16;
	portstrcpy(elementPop->atomSymbol,"S");
    portstrcpy(elementPop->atomName,"Sulfur");
    mpf_init_set_str(elementPop->atomMass,"32.065",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"112.8",10);
    mpf_init_set_str(elementPop->vaporP,"444.7",10);
    mpf_init_set_str(elementPop->density,"2.07",10);
	mpf_init_set_str(elementPop->mohsHardness,"2.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.205",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"yellow");
    mpf_init_set_str(elementPop->refractiveIndex,"1.001111",10);
    elementPop->valence = 6;
    mpf_init_set_str(elementPop->electroneg,"2.58",10);
    mpf_init_set_str(elementPop->electroAffinity,"2.1",10);
    mpf_init_set_str(elementPop->ionE1,"10.36",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"100.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.05",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.042",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.2",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7704-34-9");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &chlorine;
	Elements[16] = &chlorine;

	elementPop->atomNumber = 17;
	portstrcpy(elementPop->atomSymbol,"Cl");
    portstrcpy(elementPop->atomName,"Chlorine");
    mpf_init_set_str(elementPop->atomMass,"35.453",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-101.5",10);
    mpf_init_set_str(elementPop->vaporP,"-34.04",10);
    mpf_init_set_str(elementPop->density,"0.003214",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"206.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.0089",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"green/yellow");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000773",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"3.16",10);
    mpf_init_set_str(elementPop->electroAffinity,"3.617",10);
    mpf_init_set_str(elementPop->ionE1,"12.968",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"100.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0001",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.0017",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.12",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7782-50-5");
    portstrcpy(elementPop->CIDn,"24526");

	elementPop = &argon;
	Elements[17] = &argon;

	elementPop->atomNumber = 18;
	portstrcpy(elementPop->atomSymbol,"Ar");
    portstrcpy(elementPop->atomName,"Argon");
    mpf_init_set_str(elementPop->atomMass,"39.948",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-189.3",10);
    mpf_init_set_str(elementPop->vaporP,"-185.8",10);
    mpf_init_set_str(elementPop->density,"0.001784",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"319.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.01772",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000281",10);
    elementPop->valence = 0;
    mpf_init_set_str(elementPop->electroneg,"0.0",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"15.76",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"71.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.02",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.00015",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-37-1");
    portstrcpy(elementPop->CIDn,"23968");

	elementPop = &potassium;
	Elements[18] = &potassium;

	elementPop->atomNumber = 19;
	portstrcpy(elementPop->atomSymbol,"K");
    portstrcpy(elementPop->atomName,"Potassium");
    mpf_init_set_str(elementPop->atomMass,"39.0983",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"63.38",10);
    mpf_init_set_str(elementPop->vaporP,"759.0",10);
    mpf_init_set_str(elementPop->density,"0.856",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.4",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"2000.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"100.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"0.85",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.502",10);
    mpf_init_set_str(elementPop->ionE1,"4.341",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"182",10);
    mpf_init_set_str(elementPop->atomRadius,"220.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0003",10);
    mpf_init_set_str(elementPop->crustAbundance,"1.5",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.2",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-09-7");
    portstrcpy(elementPop->CIDn,"5462222");

	elementPop = &calcium;
	Elements[19] = &calcium;

	elementPop->atomNumber = 20;
	portstrcpy(elementPop->atomSymbol,"Ca");
    portstrcpy(elementPop->atomName,"Calcium");
    mpf_init_set_str(elementPop->atomMass,"40.078",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"842.0",10);
    mpf_init_set_str(elementPop->vaporP,"1484.0",10);
    mpf_init_set_str(elementPop->density,"1.55",10);
	mpf_init_set_str(elementPop->mohsHardness,"1.75",10);
	mpf_init_set_str(elementPop->youngsModulus,"20.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"3810",10);
	mpf_init_set_str(elementPop->thermalExp,".0000223",10);	
    mpf_init_set_str(elementPop->thermCon,"200.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.0",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0246",10);
    mpf_init_set_str(elementPop->ionE1,"6.113",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"990.0",10);
    mpf_init_set_str(elementPop->atomRadius,"180.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.007",10);
    mpf_init_set_str(elementPop->crustAbundance,"5.0",10);
    mpf_init_set_str(elementPop->humanAbundance,"1.4",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-70-2");
    portstrcpy(elementPop->CIDn,"5460231");

}
