//	Copyright (C) 2012 Travis Whitaker

#include <gmp.h>
#include <ptable.h>


char *portstrcpy(char dest[], const char source[]);

void popPtable()
{

	elementPop = &hydrogen;
	Elements[0] = &hydrogen;

	elementPop->atomNumber = 1;
	portstrcpy(elementPop->atomSymbol,"H");
    portstrcpy(elementPop->atomName,"Hydrogen");
	mpf_init_set_str(elementPop->atomMass,"1.00794",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-259.14",10);
    mpf_init_set_str(elementPop->vaporP,"-252.87",10);
    mpf_init_set_str(elementPop->density,"0.00000899",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"1270.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);
    mpf_init_set_str(elementPop->thermCon,"0.01805",10);
    elementPop->metalloid = -1;
    elementPop->magType = 0;
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000132",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"2.2",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.755",10);
    mpf_init_set_str(elementPop->ionE1,"13.598",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"285.8",10);
    mpf_init_set_str(elementPop->atomRadius,"25.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"75.0",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.15",10);
    mpf_init_set_str(elementPop->humanAbundance,"10.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1",10);
    portstrcpy(elementPop->CASn,"1333-74-0");
    portstrcpy(elementPop->CIDn,"783");

	elementPop = &helium;
	Elements[1] = &helium;

	elementPop->atomNumber = 2;
	portstrcpy(elementPop->atomSymbol,"He");
	portstrcpy(elementPop->atomName,"Helium");
	mpf_init_set_str(elementPop->atomMass,"4.002602",10);
	elementPop->phase = 0;
	mpf_init_set_str(elementPop->fusionP,"-1.0",10);
	mpf_init_set_str(elementPop->vaporP,"-268.93",10);
	mpf_init_set_str(elementPop->density,"0.0001785",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
	mpf_init_set_str(elementPop->soundSpeed,"970.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);
	mpf_init_set_str(elementPop->thermCon,"0.1513",10);
	elementPop->metalloid = 2;
	elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
	portstrcpy(elementPop->color,"colorless");
	mpf_init_set_str(elementPop->refractiveIndex,"1.000035",10);
	elementPop->valence = 0;
	mpf_init_set_str(elementPop->electroneg,"0.0",10);
	mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
	mpf_init_set_str(elementPop->ionE1,"24.587",10);
	mpf_init_set_str(elementPop->ionE2 ,"54.418",10);
	mpf_init_set_str(elementPop->ionE3,"-1.0",10);
	mpf_init_set_str(elementPop->mHc,"-1.0",10);
	mpf_init_set_str(elementPop->atomRadius,"31.0",10);
	mpf_init_set_str(elementPop->universeAbundance,"23.0",10);
	mpf_init_set_str(elementPop->crustAbundance,"0.00000055",10);
	mpf_init_set_str(elementPop->humanAbundance,"-1.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
	portstrcpy(elementPop->CASn,"7440-59-7");
	portstrcpy(elementPop->CIDn,"23987");

	elementPop = &lithium;
	Elements[2] = &lithium;

	elementPop->atomNumber = 3;
	portstrcpy(elementPop->atomSymbol,"Li");
    portstrcpy(elementPop->atomName,"Lithium");
    mpf_init_set_str(elementPop->atomMass,"6.941",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"180.54",10);
    mpf_init_set_str(elementPop->vaporP,"1342.0",10);
    mpf_init_set_str(elementPop->density,"0.535",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.6",10);
	mpf_init_set_str(elementPop->youngsModulus,"4.9",10);
    mpf_init_set_str(elementPop->soundSpeed,"6000.0",10);
	mpf_init_set_str(elementPop->thermalExp,"0.000046",10);	
    mpf_init_set_str(elementPop->thermCon,"85.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
    mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
	portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"0.98",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.618",10);
    mpf_init_set_str(elementPop->ionE1,"5.391",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"298.0",10);
    mpf_init_set_str(elementPop->atomRadius,"145.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0000006",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.0017",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.000003",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-93-2");
    portstrcpy(elementPop->CIDn,"3028194");

	elementPop = &beryllium;
	Elements[3] = &beryllium;

	elementPop->atomNumber = 4;
	portstrcpy(elementPop->atomSymbol,"Be");
    portstrcpy(elementPop->atomName,"Beryllium");
    mpf_init_set_str(elementPop->atomMass,"9.012182",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1287.0",10);
    mpf_init_set_str(elementPop->vaporP,"2480.0",10);
    mpf_init_set_str(elementPop->density,"1.858",10);
	mpf_init_set_str(elementPop->mohsHardness,"5.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"287.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"12000.0",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000113",10);	
    mpf_init_set_str(elementPop->thermCon,"190.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"0.026",10);
    portstrcpy(elementPop->color,"slate gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.57",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"9.323",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"105.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0000001",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.00019",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.00000004",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-41-7");
    portstrcpy(elementPop->CIDn,"5460467");

	elementPop = &boron;
	Elements[4] = &boron;

	elementPop->atomNumber = 5;
	portstrcpy(elementPop->atomSymbol,"B");
    portstrcpy(elementPop->atomName,"Boron");
    mpf_init_set_str(elementPop->atomMass,"10.811",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"2075.0",10);
    mpf_init_set_str(elementPop->vaporP,"4000.0",10);
    mpf_init_set_str(elementPop->density,"2.46",10);
	mpf_init_set_str(elementPop->mohsHardness,"9.3",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"16200",10);
	mpf_init_set_str(elementPop->thermalExp,"0.000006",10);	
    mpf_init_set_str(elementPop->thermCon,"27.0",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"black");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"2.04",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.277",10);
    mpf_init_set_str(elementPop->ionE1,"8.298",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"85.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0000001",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.00086",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0000007",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-42-8");
    portstrcpy(elementPop->CIDn,"5462311");

	elementPop = &carbon;
	Elements[5] = &carbon;

	elementPop->atomNumber = 6;
	portstrcpy(elementPop->atomSymbol,"C");
    portstrcpy(elementPop->atomName,"Carbon");
    mpf_init_set_str(elementPop->atomMass,"12.0107",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"3550.0",10);
    mpf_init_set_str(elementPop->vaporP,"4027.0",10);
    mpf_init_set_str(elementPop->density,"2.26",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"18350.0",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000071",10);	
    mpf_init_set_str(elementPop->thermCon,"140.0",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"black");
    mpf_init_set_str(elementPop->refractiveIndex,"2.417",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"2.55",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.595",10);
    mpf_init_set_str(elementPop->ionE1,"11.261",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"70",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.5",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.18",10);
    mpf_init_set_str(elementPop->humanAbundance,"23.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-44-0");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &nitrogen;
	Elements[6] = &nitrogen;

	elementPop->atomNumber = 7;
	portstrcpy(elementPop->atomSymbol,"N");
    portstrcpy(elementPop->atomName,"Nitrogen");
    mpf_init_set_str(elementPop->atomMass,"14.0067",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-210.1",10);
    mpf_init_set_str(elementPop->vaporP,"-195.79",10);
    mpf_init_set_str(elementPop->density,"0.001251",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"333.6",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.02583",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000298",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"3.04",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.07",10);
    mpf_init_set_str(elementPop->ionE1,"14.534",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"65.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.1",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.002",10);
    mpf_init_set_str(elementPop->humanAbundance,"2.6",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7727-37-9");
    portstrcpy(elementPop->CIDn,"947");
	
	elementPop = &oxygen;
	Elements[7] = &oxygen;

	elementPop->atomNumber = 8;
	portstrcpy(elementPop->atomSymbol,"O");
    portstrcpy(elementPop->atomName,"Oxygen");
    mpf_init_set_str(elementPop->atomMass,"15.9994",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-218.3",10);
    mpf_init_set_str(elementPop->vaporP,"-182.9",10);
    mpf_init_set_str(elementPop->density,".001429",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"317.5",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.02658",10);
    elementPop->metalloid = 2;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000271",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"3.44",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.46",10);
    mpf_init_set_str(elementPop->ionE1,"13.618",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"60.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"1.0",10);
    mpf_init_set_str(elementPop->crustAbundance,"46.0",10);
    mpf_init_set_str(elementPop->humanAbundance,"61.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7782-44-7");
    portstrcpy(elementPop->CIDn,"977");

	elementPop = &fluorine;
	Elements[8] = &fluorine;

	elementPop->atomNumber = 9;
	portstrcpy(elementPop->atomSymbol,"F");
    portstrcpy(elementPop->atomName,"Fluorine");
    mpf_init_set_str(elementPop->atomMass,"18.9984032",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-219.6",10);
    mpf_init_set_str(elementPop->vaporP,"-188.12",10);
    mpf_init_set_str(elementPop->density,"0.001696",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.0277",10);
    elementPop->metalloid = 2;
    elementPop->magType = -1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000195",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"3.98",10);
    mpf_init_set_str(elementPop->electroAffinity,"3.4",10);
    mpf_init_set_str(elementPop->ionE1,"17.422",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"50.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.00004",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.054",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0037",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7782-41-4");
    portstrcpy(elementPop->CIDn,"24524");

	elementPop = &neon;
	Elements[9] = &neon;

	elementPop->atomNumber = 10;
	portstrcpy(elementPop->atomSymbol,"Ne");
    portstrcpy(elementPop->atomName,"Neon");
    mpf_init_set_str(elementPop->atomMass,"20.1791",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-248.59",10);
    mpf_init_set_str(elementPop->vaporP,"-246.08",10);
    mpf_init_set_str(elementPop->density,"0.0009",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"936.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.0491",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000067",10);
    elementPop->valence = 0;
    mpf_init_set_str(elementPop->electroneg,"0.0",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"21.565",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"38.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.13",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.0000003",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-01-9");
    portstrcpy(elementPop->CIDn,"23935");

	elementPop = &sodium;
	Elements[10] = &sodium;

	elementPop->atomNumber = 11;
	portstrcpy(elementPop->atomSymbol,"Na");
    portstrcpy(elementPop->atomName,"Sodium");
    mpf_init_set_str(elementPop->atomMass,"22.98976928",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"97.72",10);
    mpf_init_set_str(elementPop->vaporP,"883",10);
    mpf_init_set_str(elementPop->density,"0.968",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"10",10);
    mpf_init_set_str(elementPop->soundSpeed,"3200",10);
	mpf_init_set_str(elementPop->thermalExp,"0.000071",10);	
    mpf_init_set_str(elementPop->thermCon,"140",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"0.93",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.547",10);
    mpf_init_set_str(elementPop->ionE1,"5.139",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"180.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".002",10);
    mpf_init_set_str(elementPop->crustAbundance,"2.3",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.14",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-23-5");
    portstrcpy(elementPop->CIDn,"5360545");

	elementPop = &magnesium;
	Elements[11] = &magnesium;

	elementPop->atomNumber = 12;
	portstrcpy(elementPop->atomSymbol,"Mg");
    portstrcpy(elementPop->atomName,"Magnesium");
    mpf_init_set_str(elementPop->atomMass,"24.3050",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"650.0",10);
    mpf_init_set_str(elementPop->vaporP,"1090.0",10);
    mpf_init_set_str(elementPop->density,"1.738",10);
	mpf_init_set_str(elementPop->mohsHardness,"2.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"45",10);
    mpf_init_set_str(elementPop->soundSpeed,"4602",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000082",10);	
    mpf_init_set_str(elementPop->thermCon,"160.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.31",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"7.646",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"66.08",10);
    mpf_init_set_str(elementPop->atomRadius,"150.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".06",10);
    mpf_init_set_str(elementPop->crustAbundance,"2.9",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.027",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-95-4");
    portstrcpy(elementPop->CIDn,"5462224");

	elementPop = &aluminium;
	Elements[12] = &aluminium;

	elementPop->atomNumber = 13;
	portstrcpy(elementPop->atomSymbol,"Al");
    portstrcpy(elementPop->atomName,"Aluminium");
    mpf_init_set_str(elementPop->atomMass,"26.9815286",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"660.32",10);
    mpf_init_set_str(elementPop->vaporP,"2519.0",10);
    mpf_init_set_str(elementPop->density,"2.7",10);
	mpf_init_set_str(elementPop->mohsHardness,"2.75",10);
	mpf_init_set_str(elementPop->youngsModulus,"70",10);
    mpf_init_set_str(elementPop->soundSpeed,"5100",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000231",10);	
    mpf_init_set_str(elementPop->thermCon,"235",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"1.175",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"1.61",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.44",10);
    mpf_init_set_str(elementPop->ionE1,"5.985",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"125.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.005",10);
    mpf_init_set_str(elementPop->crustAbundance,"8.1",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.00009",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7429-90-5");
    portstrcpy(elementPop->CIDn,"5359268");

	elementPop = &silicon;
	Elements[13] = &silicon;

	elementPop->atomNumber = 14;
	portstrcpy(elementPop->atomSymbol,"Si");
    portstrcpy(elementPop->atomName,"Silicon");
    mpf_init_set_str(elementPop->atomMass,"28.0855",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"141.04",10);
    mpf_init_set_str(elementPop->vaporP,"2900.0",10);
    mpf_init_set_str(elementPop->density,"2.33",10);
	mpf_init_set_str(elementPop->mohsHardness,"6.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"47",10);
    mpf_init_set_str(elementPop->soundSpeed,"2200",10);
	mpf_init_set_str(elementPop->thermalExp,"0.0000026",10);	
    mpf_init_set_str(elementPop->thermCon,"150.0",10);
    elementPop->metalloid = 1;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"1.9",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.385",10);
    mpf_init_set_str(elementPop->ionE1,"8.151",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"9055.0",10);
    mpf_init_set_str(elementPop->atomRadius,"110.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.07",10);
    mpf_init_set_str(elementPop->crustAbundance,"27.0",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.026",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-21-3");
    portstrcpy(elementPop->CIDn,"5461123");


	elementPop = &phosphorus;
	Elements[14] = &phosphorus;

	elementPop->atomNumber = 15;
	portstrcpy(elementPop->atomSymbol,"P");
    portstrcpy(elementPop->atomName,"Phosphorus");
    mpf_init_set_str(elementPop->atomMass,"30.973762",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"-1.0",10);
    mpf_init_set_str(elementPop->vaporP,"-1.0",10);
    mpf_init_set_str(elementPop->density,"-1.0",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.236",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"white/black/red");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"2.19",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.75",10);
    mpf_init_set_str(elementPop->ionE1,"10.487",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"100.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0007",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.099",10);
    mpf_init_set_str(elementPop->humanAbundance,"1.1",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7723-14-0");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &sulfur;
	Elements[15] = &sulfur;

	elementPop->atomNumber = 16;
	portstrcpy(elementPop->atomSymbol,"S");
    portstrcpy(elementPop->atomName,"Sulfur");
    mpf_init_set_str(elementPop->atomMass,"32.065",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"112.8",10);
    mpf_init_set_str(elementPop->vaporP,"444.7",10);
    mpf_init_set_str(elementPop->density,"2.07",10);
	mpf_init_set_str(elementPop->mohsHardness,"2.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.205",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"yellow");
    mpf_init_set_str(elementPop->refractiveIndex,"1.001111",10);
    elementPop->valence = 6;
    mpf_init_set_str(elementPop->electroneg,"2.58",10);
    mpf_init_set_str(elementPop->electroAffinity,"2.1",10);
    mpf_init_set_str(elementPop->ionE1,"10.36",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"100.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.05",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.042",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.2",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7704-34-9");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &chlorine;
	Elements[16] = &chlorine;

	elementPop->atomNumber = 17;
	portstrcpy(elementPop->atomSymbol,"Cl");
    portstrcpy(elementPop->atomName,"Chlorine");
    mpf_init_set_str(elementPop->atomMass,"35.453",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-101.5",10);
    mpf_init_set_str(elementPop->vaporP,"-34.04",10);
    mpf_init_set_str(elementPop->density,"0.003214",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"206.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.0089",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"green/yellow");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000773",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"3.16",10);
    mpf_init_set_str(elementPop->electroAffinity,"3.617",10);
    mpf_init_set_str(elementPop->ionE1,"12.968",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"100.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0001",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.0017",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.12",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7782-50-5");
    portstrcpy(elementPop->CIDn,"24526");

	elementPop = &argon;
	Elements[17] = &argon;

	elementPop->atomNumber = 18;
	portstrcpy(elementPop->atomSymbol,"Ar");
    portstrcpy(elementPop->atomName,"Argon");
    mpf_init_set_str(elementPop->atomMass,"39.948",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-189.3",10);
    mpf_init_set_str(elementPop->vaporP,"-185.8",10);
    mpf_init_set_str(elementPop->density,"0.001784",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1.0",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"319.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"0.01772",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000281",10);
    elementPop->valence = 0;
    mpf_init_set_str(elementPop->electroneg,"0.0",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0",10);
    mpf_init_set_str(elementPop->ionE1,"15.76",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1.0",10);
    mpf_init_set_str(elementPop->atomRadius,"71.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.02",10);
    mpf_init_set_str(elementPop->crustAbundance,"0.00015",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-37-1");
    portstrcpy(elementPop->CIDn,"23968");

	elementPop = &potassium;
	Elements[18] = &potassium;

	elementPop->atomNumber = 19;
	portstrcpy(elementPop->atomSymbol,"K");
    portstrcpy(elementPop->atomName,"Potassium");
    mpf_init_set_str(elementPop->atomMass,"39.0983",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"63.38",10);
    mpf_init_set_str(elementPop->vaporP,"759.0",10);
    mpf_init_set_str(elementPop->density,"0.856",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.4",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"2000.0",10);
	mpf_init_set_str(elementPop->thermalExp,"-1.0",10);	
    mpf_init_set_str(elementPop->thermCon,"100.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"0.85",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.502",10);
    mpf_init_set_str(elementPop->ionE1,"4.341",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"182",10);
    mpf_init_set_str(elementPop->atomRadius,"220.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.0003",10);
    mpf_init_set_str(elementPop->crustAbundance,"1.5",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.2",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-09-7");
    portstrcpy(elementPop->CIDn,"5462222");

	elementPop = &calcium;
	Elements[19] = &calcium;

	elementPop->atomNumber = 20;
	portstrcpy(elementPop->atomSymbol,"Ca");
    portstrcpy(elementPop->atomName,"Calcium");
    mpf_init_set_str(elementPop->atomMass,"40.078",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"842.0",10);
    mpf_init_set_str(elementPop->vaporP,"1484.0",10);
    mpf_init_set_str(elementPop->density,"1.55",10);
	mpf_init_set_str(elementPop->mohsHardness,"1.75",10);
	mpf_init_set_str(elementPop->youngsModulus,"20.0",10);
    mpf_init_set_str(elementPop->soundSpeed,"3810",10);
	mpf_init_set_str(elementPop->thermalExp,".0000223",10);	
    mpf_init_set_str(elementPop->thermCon,"200.0",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1.0",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.0",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0246",10);
    mpf_init_set_str(elementPop->ionE1,"6.113",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"990.0",10);
    mpf_init_set_str(elementPop->atomRadius,"180.0",10);
    mpf_init_set_str(elementPop->universeAbundance,"0.007",10);
    mpf_init_set_str(elementPop->crustAbundance,"5.0",10);
    mpf_init_set_str(elementPop->humanAbundance,"1.4",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-70-2");
    portstrcpy(elementPop->CIDn,"5460231");

	elementPop = &scandium;
	Elements[20] = &scandium;

	elementPop->atomNumber = 21;
	portstrcpy(elementPop->atomSymbol,"Sc");
    portstrcpy(elementPop->atomName,"Scandium");
    mpf_init_set_str(elementPop->atomMass,"44.955912",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1541",10);
    mpf_init_set_str(elementPop->vaporP,"2830",10);
    mpf_init_set_str(elementPop->density,"2.985",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1",10);
	mpf_init_set_str(elementPop->youngsModulus,"74",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1",10);
	mpf_init_set_str(elementPop->thermalExp,".0000102",10);	
    mpf_init_set_str(elementPop->thermCon,"16",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"0.05",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"1.36",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.188",10);
    mpf_init_set_str(elementPop->ionE1,"6.562",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"160.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".000003",10);
    mpf_init_set_str(elementPop->crustAbundance,".0026",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-20-2");
    portstrcpy(elementPop->CIDn,"23952");

	elementPop = &titanium;
	Elements[21] = &titanium;

	elementPop->atomNumber = 22;
	portstrcpy(elementPop->atomSymbol,"Ti");
    portstrcpy(elementPop->atomName,"Titanium");
    mpf_init_set_str(elementPop->atomMass,"47.867",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1668",10);
    mpf_init_set_str(elementPop->vaporP,"3287",10);
    mpf_init_set_str(elementPop->density,"4.507",10);
	mpf_init_set_str(elementPop->mohsHardness,"6",10);
	mpf_init_set_str(elementPop->youngsModulus,"116",10);
    mpf_init_set_str(elementPop->soundSpeed,"4140",10);
	mpf_init_set_str(elementPop->thermalExp,".0000086",10);	
    mpf_init_set_str(elementPop->thermCon,"22",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"0.4",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"1.54",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.079",10);
    mpf_init_set_str(elementPop->ionE1,"6.828",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"140.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".0003",10);
    mpf_init_set_str(elementPop->crustAbundance,".66",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-32-6");
    portstrcpy(elementPop->CIDn,"23963");

	elementPop = &vanadium;
	Elements[22] = &vanadium;

	elementPop->atomNumber = 23;
	portstrcpy(elementPop->atomSymbol,"V");
    portstrcpy(elementPop->atomName,"Vanadium");
    mpf_init_set_str(elementPop->atomMass,"50.9415",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1910",10);
    mpf_init_set_str(elementPop->vaporP,"3407",10);
    mpf_init_set_str(elementPop->density,"6.11",10);
	mpf_init_set_str(elementPop->mohsHardness,"7",10);
	mpf_init_set_str(elementPop->youngsModulus,"128",10);
    mpf_init_set_str(elementPop->soundSpeed,"4560",10);
	mpf_init_set_str(elementPop->thermalExp,".0000084",10);	
    mpf_init_set_str(elementPop->thermCon,"31",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"5.4",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"1.63",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.524",10);
    mpf_init_set_str(elementPop->ionE1,"6.746",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"135.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".0001",10);
    mpf_init_set_str(elementPop->crustAbundance,".019",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.000003",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-62-2");
    portstrcpy(elementPop->CIDn,"23990");

	elementPop = &chromium;
	Elements[23] = &chromium;

	elementPop->atomNumber = 24;
	portstrcpy(elementPop->atomSymbol,"Cr");
    portstrcpy(elementPop->atomName,"Chromium");
    mpf_init_set_str(elementPop->atomMass,"51.9961",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1907",10);
    mpf_init_set_str(elementPop->vaporP,"2671",10);
    mpf_init_set_str(elementPop->density,"7.14",10);
	mpf_init_set_str(elementPop->mohsHardness,"8.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"279",10);
    mpf_init_set_str(elementPop->soundSpeed,"5940",10);
	mpf_init_set_str(elementPop->thermalExp,".0000049",10);	
    mpf_init_set_str(elementPop->thermCon,"94",10);
    elementPop->metalloid = 0;
    elementPop->magType = 3;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 6;
    mpf_init_set_str(elementPop->electroneg,"1.66",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.666",10);//lol
    mpf_init_set_str(elementPop->ionE1,"6.767",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"140.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".0015",10);
    mpf_init_set_str(elementPop->crustAbundance,".014",10);
    mpf_init_set_str(elementPop->humanAbundance,"0.000003",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-47-3");
    portstrcpy(elementPop->CIDn,"23976");

	elementPop = &manganese;
	Elements[24] = &manganese;

	elementPop->atomNumber = 25;
	portstrcpy(elementPop->atomSymbol,"Mn");
    portstrcpy(elementPop->atomName,"Manganese");
    mpf_init_set_str(elementPop->atomMass,"54.938045",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1246",10);
    mpf_init_set_str(elementPop->vaporP,"2061",10);
    mpf_init_set_str(elementPop->density,"7.47",10);
	mpf_init_set_str(elementPop->mohsHardness,"6",10);
	mpf_init_set_str(elementPop->youngsModulus,"198",10);
    mpf_init_set_str(elementPop->soundSpeed,"5150",10);
	mpf_init_set_str(elementPop->thermalExp,".0000217",10);	
    mpf_init_set_str(elementPop->thermCon,"7.8",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"1.55",10);
    mpf_init_set_str(elementPop->electroAffinity,"0",10);
    mpf_init_set_str(elementPop->ionE1,"7.424",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"140.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".0008",10);
    mpf_init_set_str(elementPop->crustAbundance,".11",10);
    mpf_init_set_str(elementPop->humanAbundance,".00002",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-96-5");
    portstrcpy(elementPop->CIDn,"23930");

	elementPop = &iron;
	Elements[25] = &iron;

	elementPop->atomNumber = 26;
	portstrcpy(elementPop->atomSymbol,"Fe");
    portstrcpy(elementPop->atomName,"Iron");
    mpf_init_set_str(elementPop->atomMass,"55.845",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1538",10);
    mpf_init_set_str(elementPop->vaporP,"2861",10);
    mpf_init_set_str(elementPop->density,"7.874",10);
	mpf_init_set_str(elementPop->mohsHardness,"4",10);
	mpf_init_set_str(elementPop->youngsModulus,"211",10);
    mpf_init_set_str(elementPop->soundSpeed,"4910",10);
	mpf_init_set_str(elementPop->thermalExp,".0000118",10);	
    mpf_init_set_str(elementPop->thermCon,"80",10);
    elementPop->metalloid = 0;
    elementPop->magType = 2;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"1.83",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.163",10);
    mpf_init_set_str(elementPop->ionE1,"7.903",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"140.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".11",10);
    mpf_init_set_str(elementPop->crustAbundance,"6.3",10);
    mpf_init_set_str(elementPop->humanAbundance,".006",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-89-6");
    portstrcpy(elementPop->CIDn,"23925");

	elementPop = &cobalt;
	Elements[26] = &cobalt;

	elementPop->atomNumber = 27;
	portstrcpy(elementPop->atomSymbol,"Co");
    portstrcpy(elementPop->atomName,"Cobalt");
    mpf_init_set_str(elementPop->atomMass,"58.933195",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1495",10);
    mpf_init_set_str(elementPop->vaporP,"2927",10);
    mpf_init_set_str(elementPop->density,"8.9",10);
	mpf_init_set_str(elementPop->mohsHardness,"5",10);
	mpf_init_set_str(elementPop->youngsModulus,"209",10);
    mpf_init_set_str(elementPop->soundSpeed,"4720",10);
	mpf_init_set_str(elementPop->thermalExp,".000013",10);	
    mpf_init_set_str(elementPop->thermCon,"100",10);
    elementPop->metalloid = 0;
    elementPop->magType = 2;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"1.88",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.66",10);
    mpf_init_set_str(elementPop->ionE1,"7.881",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"135.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".0003",10);
    mpf_init_set_str(elementPop->crustAbundance,".003",10);
    mpf_init_set_str(elementPop->humanAbundance,".000002",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-48-4");
    portstrcpy(elementPop->CIDn,"104730");

	elementPop = &nickel;
	Elements[27] = &nickel;

	elementPop->atomNumber = 28;
	portstrcpy(elementPop->atomSymbol,"Ni");
    portstrcpy(elementPop->atomName,"Nickel");
    mpf_init_set_str(elementPop->atomMass,"58.6934",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1455",10);
    mpf_init_set_str(elementPop->vaporP,"2913",10);
    mpf_init_set_str(elementPop->density,"8.908",10);
	mpf_init_set_str(elementPop->mohsHardness,"4",10);
	mpf_init_set_str(elementPop->youngsModulus,"200",10);
    mpf_init_set_str(elementPop->soundSpeed,"4970",10);
	mpf_init_set_str(elementPop->thermalExp,".0000134",10);	
    mpf_init_set_str(elementPop->thermCon,"91",10);
    elementPop->metalloid = 0;
    elementPop->magType = 2;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.91",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.16",10);
    mpf_init_set_str(elementPop->ionE1,"7.64",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"135.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".006",10);
    mpf_init_set_str(elementPop->crustAbundance,".0089",10);
    mpf_init_set_str(elementPop->humanAbundance,".00001",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-02-0");
    portstrcpy(elementPop->CIDn,"935");

	elementPop = &copper;
	Elements[28] = &copper;

	elementPop->atomNumber = 29;
	portstrcpy(elementPop->atomSymbol,"Cu");
    portstrcpy(elementPop->atomName,"Copper");
    mpf_init_set_str(elementPop->atomMass,"63.546",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1084.62",10);
    mpf_init_set_str(elementPop->vaporP,"2927",10);
    mpf_init_set_str(elementPop->density,"8.96",10);
	mpf_init_set_str(elementPop->mohsHardness,"3",10);
	mpf_init_set_str(elementPop->youngsModulus,"130",10);
    mpf_init_set_str(elementPop->soundSpeed,"3570",10);
	mpf_init_set_str(elementPop->thermalExp,".0000165",10);	
    mpf_init_set_str(elementPop->thermCon,"400",10);
    elementPop->metalloid = 0;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"copper");//:P
    mpf_init_set_str(elementPop->refractiveIndex,"-1.0",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.9",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.227",10);
    mpf_init_set_str(elementPop->ionE1,"7.727",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"135.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".000006",10);
    mpf_init_set_str(elementPop->crustAbundance,".0068",10);
    mpf_init_set_str(elementPop->humanAbundance,".0001",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-50-8");
    portstrcpy(elementPop->CIDn,"23978");

	elementPop = &zinc;
	Elements[29] = &zinc;

	elementPop->atomNumber = 30;
	portstrcpy(elementPop->atomSymbol,"Zn");
    portstrcpy(elementPop->atomName,"Zinc");
    mpf_init_set_str(elementPop->atomMass,"65.38",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"419.53",10);
    mpf_init_set_str(elementPop->vaporP,"907",10);
    mpf_init_set_str(elementPop->density,"7.14",10);
	mpf_init_set_str(elementPop->mohsHardness,"2.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"108",10);
    mpf_init_set_str(elementPop->soundSpeed,"3700",10);
	mpf_init_set_str(elementPop->thermalExp,".0000302",10);	
    mpf_init_set_str(elementPop->thermCon,"120",10);
    elementPop->metalloid = 0;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"0.85",10);
    portstrcpy(elementPop->color,"slate gray");
    mpf_init_set_str(elementPop->refractiveIndex,"1.00205",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"1.65",10);
    mpf_init_set_str(elementPop->electroAffinity,"0",10);
    mpf_init_set_str(elementPop->ionE1,"9.394",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"135.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".00003",10);
    mpf_init_set_str(elementPop->crustAbundance,".0078",10);
    mpf_init_set_str(elementPop->humanAbundance,".0033",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-66-6");
    portstrcpy(elementPop->CIDn,"23994");

	elementPop = &gallium;
	Elements[30] = &gallium;

	elementPop->atomNumber = 31;
	portstrcpy(elementPop->atomSymbol,"Ga");
    portstrcpy(elementPop->atomName,"Gallium");
    mpf_init_set_str(elementPop->atomMass,"69.723",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"29.76",10);
    mpf_init_set_str(elementPop->vaporP,"2204",10);
    mpf_init_set_str(elementPop->density,"5.904",10);
	mpf_init_set_str(elementPop->mohsHardness,"1.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1",10);
    mpf_init_set_str(elementPop->soundSpeed,"2740",10);
	mpf_init_set_str(elementPop->thermalExp,".00012",10);	
    mpf_init_set_str(elementPop->thermCon,"29",10);
    elementPop->metalloid = 0;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"1.083",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"1.00205",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"1.81",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.3",10);
    mpf_init_set_str(elementPop->ionE1,"5.999",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"130.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".000001",10);
    mpf_init_set_str(elementPop->crustAbundance,".0019",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-55-3");
    portstrcpy(elementPop->CIDn,"5360835");

	elementPop = &germanium;
	Elements[31] = &germanium;

	elementPop->atomNumber = 32;
	portstrcpy(elementPop->atomSymbol,"Ge");
    portstrcpy(elementPop->atomName,"Germanium");
    mpf_init_set_str(elementPop->atomMass,"72.63",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"938.3",10);
    mpf_init_set_str(elementPop->vaporP,"2820",10);
    mpf_init_set_str(elementPop->density,"5.323",10);
	mpf_init_set_str(elementPop->mohsHardness,"6",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1",10);
    mpf_init_set_str(elementPop->soundSpeed,"5400",10);
	mpf_init_set_str(elementPop->thermalExp,".000006",10);	
    mpf_init_set_str(elementPop->thermCon,"60",10);
    elementPop->metalloid = 1;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"2.01",10);
    mpf_init_set_str(elementPop->electroAffinity,"1.23",10);
    mpf_init_set_str(elementPop->ionE1,"7.9",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"536",10);
    mpf_init_set_str(elementPop->atomRadius,"125.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".00002",10);
    mpf_init_set_str(elementPop->crustAbundance,".00014",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-56-4");
    portstrcpy(elementPop->CIDn,"6326954");

	elementPop = &arsenic;
	Elements[32] = &arsenic;

	elementPop->atomNumber = 33;
	portstrcpy(elementPop->atomSymbol,"As");
    portstrcpy(elementPop->atomName,"Arsenic");
    mpf_init_set_str(elementPop->atomMass,"84.92160",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"817",10);
    mpf_init_set_str(elementPop->vaporP,"616",10);
    mpf_init_set_str(elementPop->density,"5.727",10);
	mpf_init_set_str(elementPop->mohsHardness,"3.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"8",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1",10);
	mpf_init_set_str(elementPop->thermalExp,"-1",10);	
    mpf_init_set_str(elementPop->thermCon,"50",10);
    elementPop->metalloid = 1;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"1.001552",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"2.18",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.81",10);
    mpf_init_set_str(elementPop->ionE1,"9.815",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"115.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".0000008",10);
    mpf_init_set_str(elementPop->crustAbundance,".00021",10);
    mpf_init_set_str(elementPop->humanAbundance,".000005",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-38-2");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &selenium;
	Elements[33] = &selenium;

	elementPop->atomNumber = 34;
	portstrcpy(elementPop->atomSymbol,"Se");
    portstrcpy(elementPop->atomName,"Selenium");
    mpf_init_set_str(elementPop->atomMass,"78.96",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"217",10);
    mpf_init_set_str(elementPop->vaporP,"684.9",10);
    mpf_init_set_str(elementPop->density,"4.81",10);
	mpf_init_set_str(elementPop->mohsHardness,"2",10);
	mpf_init_set_str(elementPop->youngsModulus,"10",10);
    mpf_init_set_str(elementPop->soundSpeed,"3350",10);
	mpf_init_set_str(elementPop->thermalExp,"-1",10);	
    mpf_init_set_str(elementPop->thermCon,"0.52",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"gray/red/black");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000895",10);
    elementPop->valence = 6;
    mpf_init_set_str(elementPop->electroneg,"2.55",10);
    mpf_init_set_str(elementPop->electroAffinity,"2.021",10);
    mpf_init_set_str(elementPop->ionE1,"9.753",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"115.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".000003",10);
    mpf_init_set_str(elementPop->crustAbundance,".000005",10);
    mpf_init_set_str(elementPop->humanAbundance,".000005",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7782-49-2");
    portstrcpy(elementPop->CIDn,"N/A");

	elementPop = &bromine;
	Elements[34] = &bromine;

	elementPop->atomNumber = 35;
	portstrcpy(elementPop->atomSymbol,"Br");
    portstrcpy(elementPop->atomName,"Bromine");
    mpf_init_set_str(elementPop->atomMass,"79.904",10);
    elementPop->phase = 1;
    mpf_init_set_str(elementPop->fusionP,"-7.3",10);
    mpf_init_set_str(elementPop->vaporP,"59",10);
    mpf_init_set_str(elementPop->density,"3.12",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1",10);
	mpf_init_set_str(elementPop->thermalExp,"-1",10);	
    mpf_init_set_str(elementPop->thermCon,"0.12",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"red/brown");
    mpf_init_set_str(elementPop->refractiveIndex,"1.001132",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"2.96",10);
    mpf_init_set_str(elementPop->electroAffinity,"3.364",10);
    mpf_init_set_str(elementPop->ionE1,"11.814",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"115.0",10);
    mpf_init_set_str(elementPop->universeAbundance,".0000007",10);
    mpf_init_set_str(elementPop->crustAbundance,".0003",10);
    mpf_init_set_str(elementPop->humanAbundance,".00029",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7726-95-6");
    portstrcpy(elementPop->CIDn,"23304");

	elementPop = &krypton;
	Elements[35] = &krypton;

	elementPop->atomNumber = 36;
	portstrcpy(elementPop->atomSymbol,"Kr");
    portstrcpy(elementPop->atomName,"Krypton");
    mpf_init_set_str(elementPop->atomMass,"83.798",10);
    elementPop->phase = 0;
    mpf_init_set_str(elementPop->fusionP,"-157.36",10);
    mpf_init_set_str(elementPop->vaporP,"-153.22",10);
    mpf_init_set_str(elementPop->density,"0.00375",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1",10);
    mpf_init_set_str(elementPop->soundSpeed,"1120",10);
	mpf_init_set_str(elementPop->thermalExp,"-1",10);	
    mpf_init_set_str(elementPop->thermCon,"0.00943",10);
    elementPop->metalloid = 2;
    elementPop->magType = 0;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"colorless");
    mpf_init_set_str(elementPop->refractiveIndex,"1.000427",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"3",10);
    mpf_init_set_str(elementPop->electroAffinity,"0",10);
    mpf_init_set_str(elementPop->ionE1,"14",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"88",10);
    mpf_init_set_str(elementPop->universeAbundance,".000004",10);
    mpf_init_set_str(elementPop->crustAbundance,".000000015",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-90-9");
    portstrcpy(elementPop->CIDn,"5416");

	elementPop = &rubidium;
	Elements[36] = &rubidium;

	elementPop->atomNumber = 37;
	portstrcpy(elementPop->atomSymbol,"Rb");
    portstrcpy(elementPop->atomName,"Rubidium");
    mpf_init_set_str(elementPop->atomMass,"85.4678",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"39.31",10);
    mpf_init_set_str(elementPop->vaporP,"668",10);
    mpf_init_set_str(elementPop->density,"1.532",10);
	mpf_init_set_str(elementPop->mohsHardness,"0.3",10);
	mpf_init_set_str(elementPop->youngsModulus,"2.4",10);
    mpf_init_set_str(elementPop->soundSpeed,"1300",10);
	mpf_init_set_str(elementPop->thermalExp,"-1",10);	
    mpf_init_set_str(elementPop->thermCon,"58",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 1;
    mpf_init_set_str(elementPop->electroneg,"0.82",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.486",10);
    mpf_init_set_str(elementPop->ionE1,"4.177",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"235",10);
    mpf_init_set_str(elementPop->universeAbundance,".000001",10);
    mpf_init_set_str(elementPop->crustAbundance,".006",10);
    mpf_init_set_str(elementPop->humanAbundance,".00046",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-17-7");
    portstrcpy(elementPop->CIDn,"5357696");

	elementPop = &strontium;
	Elements[37] = &strontium;

	elementPop->atomNumber = 38;
	portstrcpy(elementPop->atomSymbol,"Sr");
    portstrcpy(elementPop->atomName,"Strontium");
    mpf_init_set_str(elementPop->atomMass,"87.62",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"777",10);
    mpf_init_set_str(elementPop->vaporP,"1382",10);
    mpf_init_set_str(elementPop->density,"2.63",10);
	mpf_init_set_str(elementPop->mohsHardness,"1.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1",10);
	mpf_init_set_str(elementPop->thermalExp,".0000225",10);	
    mpf_init_set_str(elementPop->thermCon,"35",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"-1",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 2;
    mpf_init_set_str(elementPop->electroneg,"0.95",10);
    mpf_init_set_str(elementPop->electroAffinity,"0.0521",10);
    mpf_init_set_str(elementPop->ionE1,"5.695",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"200",10);
    mpf_init_set_str(elementPop->universeAbundance,".000004",10);
    mpf_init_set_str(elementPop->crustAbundance,".036",10);
    mpf_init_set_str(elementPop->humanAbundance,".00046",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-24-6");
    portstrcpy(elementPop->CIDn,"5359327");

	elementPop = &yttrium;
	Elements[38] = &yttrium;

	elementPop->atomNumber = 39;
	portstrcpy(elementPop->atomSymbol,"Y");
    portstrcpy(elementPop->atomName,"Yttrium");
    mpf_init_set_str(elementPop->atomMass,"88.90585",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1526",10);
    mpf_init_set_str(elementPop->vaporP,"3345",10);
    mpf_init_set_str(elementPop->density,"4.472",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1",10);
	mpf_init_set_str(elementPop->youngsModulus,"64",10);
    mpf_init_set_str(elementPop->soundSpeed,"3300",10);
	mpf_init_set_str(elementPop->thermalExp,".0000106",10);	
    mpf_init_set_str(elementPop->thermCon,"17",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"1.3",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 3;
    mpf_init_set_str(elementPop->electroneg,"1.22",10);
    mpf_init_set_str(elementPop->electroAffinity,".307",10);
    mpf_init_set_str(elementPop->ionE1,"6.2",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"180",10);
    mpf_init_set_str(elementPop->universeAbundance,".0000007",10);
    mpf_init_set_str(elementPop->crustAbundance,".0029",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-65-5");
    portstrcpy(elementPop->CIDn,"233993");

	elementPop = &zirconium;
	Elements[39] = &zirconium;

	elementPop->atomNumber = 40;
	portstrcpy(elementPop->atomSymbol,"Zr");
    portstrcpy(elementPop->atomName,"Zirconium");
    mpf_init_set_str(elementPop->atomMass,"91.224",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"1855",10);
    mpf_init_set_str(elementPop->vaporP,"4409",10);
    mpf_init_set_str(elementPop->density,"6.511",10);
	mpf_init_set_str(elementPop->mohsHardness,"5",10);
	mpf_init_set_str(elementPop->youngsModulus,"68",10);
    mpf_init_set_str(elementPop->soundSpeed,"3800",10);
	mpf_init_set_str(elementPop->thermalExp,".0000057",10);	
    mpf_init_set_str(elementPop->thermCon,"23",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"0.61",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 4;
    mpf_init_set_str(elementPop->electroneg,"1.33",10);
    mpf_init_set_str(elementPop->electroAffinity,".426",10);
    mpf_init_set_str(elementPop->ionE1,"6.634",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"155",10);
    mpf_init_set_str(elementPop->universeAbundance,".000005",10);
    mpf_init_set_str(elementPop->crustAbundance,".013",10);
    mpf_init_set_str(elementPop->humanAbundance,".000005",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-67-7");
    portstrcpy(elementPop->CIDn,"239995");

	elementPop = &niobium;
	Elements[40] = &niobium;

	elementPop->atomNumber = 41;
	portstrcpy(elementPop->atomSymbol,"Nb");
    portstrcpy(elementPop->atomName,"Niobium");
    mpf_init_set_str(elementPop->atomMass,"92.90638",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"2477",10);
    mpf_init_set_str(elementPop->vaporP,"4744",10);
    mpf_init_set_str(elementPop->density,"8.57",10);
	mpf_init_set_str(elementPop->mohsHardness,"6",10);
	mpf_init_set_str(elementPop->youngsModulus,"105",10);
    mpf_init_set_str(elementPop->soundSpeed,"3480",10);
	mpf_init_set_str(elementPop->thermalExp,".0000073",10);	
    mpf_init_set_str(elementPop->thermCon,"54",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"9.25",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 5;
    mpf_init_set_str(elementPop->electroneg,"1.6",10);
    mpf_init_set_str(elementPop->electroAffinity,".892",10);
    mpf_init_set_str(elementPop->ionE1,"6.759",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"145",10);
    mpf_init_set_str(elementPop->universeAbundance,".0000002",10);
    mpf_init_set_str(elementPop->crustAbundance,".0017",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7440-03-1");
    portstrcpy(elementPop->CIDn,"23936");

	elementPop = &molybdenum;
	Elements[41] = &molybdenum;

	elementPop->atomNumber = 42;
	portstrcpy(elementPop->atomSymbol,"Mo");
    portstrcpy(elementPop->atomName,"Molybdenum");
    mpf_init_set_str(elementPop->atomMass,"95.96",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"2423",10);
    mpf_init_set_str(elementPop->vaporP,"4639",10);
    mpf_init_set_str(elementPop->density,"10.28",10);
	mpf_init_set_str(elementPop->mohsHardness,"5.5",10);
	mpf_init_set_str(elementPop->youngsModulus,"329",10);
    mpf_init_set_str(elementPop->soundSpeed,"6190",10);
	mpf_init_set_str(elementPop->thermalExp,".0000048",10);	
    mpf_init_set_str(elementPop->thermCon,"139",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,".915",10);
    portstrcpy(elementPop->color,"gray");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 6;
    mpf_init_set_str(elementPop->electroneg,"2.16",10);
    mpf_init_set_str(elementPop->electroAffinity,".745",10);
    mpf_init_set_str(elementPop->ionE1,"7.092",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"145",10);
    mpf_init_set_str(elementPop->universeAbundance,".0000005",10);
    mpf_init_set_str(elementPop->crustAbundance,".00011",10);
    mpf_init_set_str(elementPop->humanAbundance,".00001",10);
	mpf_init_set_str(elementPop->halfLifeYears,"-1.0",10);
    portstrcpy(elementPop->CASn,"7439-98-7");
    portstrcpy(elementPop->CIDn,"23932");

	elementPop = &technetium;
	Elements[42] = &technetium;

	elementPop->atomNumber = 43;
	portstrcpy(elementPop->atomSymbol,"Tc");
    portstrcpy(elementPop->atomName,"Technetium");
    mpf_init_set_str(elementPop->atomMass,"97.907215966",10);
    elementPop->phase = 2;
    mpf_init_set_str(elementPop->fusionP,"2157",10);
    mpf_init_set_str(elementPop->vaporP,"4265",10);
    mpf_init_set_str(elementPop->density,"11.5",10);
	mpf_init_set_str(elementPop->mohsHardness,"-1",10);
	mpf_init_set_str(elementPop->youngsModulus,"-1",10);
    mpf_init_set_str(elementPop->soundSpeed,"-1",10);
	mpf_init_set_str(elementPop->thermalExp,"-1",10);	
    mpf_init_set_str(elementPop->thermCon,"51",10);
    elementPop->metalloid = 0;
    elementPop->magType = 1;
	mpf_init_set_str(elementPop->superconductingPoint,"7.8",10);
    portstrcpy(elementPop->color,"silver");
    mpf_init_set_str(elementPop->refractiveIndex,"-1",10);
    elementPop->valence = 6;
    mpf_init_set_str(elementPop->electroneg,"1.9",10);
    mpf_init_set_str(elementPop->electroAffinity,".55",10);
    mpf_init_set_str(elementPop->ionE1,"7.28",10);
    mpf_init_set_str(elementPop->ionE2,"-1.0",10);
    mpf_init_set_str(elementPop->ionE3,"-1.0",10);
    mpf_init_set_str(elementPop->mHc,"-1",10);
    mpf_init_set_str(elementPop->atomRadius,"135",10);
    mpf_init_set_str(elementPop->universeAbundance,"-1",10);
    mpf_init_set_str(elementPop->crustAbundance,"0",10);
    mpf_init_set_str(elementPop->humanAbundance,"0",10);
	mpf_init_set_str(elementPop->halfLifeYears,"4100000",10);
    portstrcpy(elementPop->CASn,"7440-26-8");
    portstrcpy(elementPop->CIDn,"N/A");


}
